/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PibliyeRouteImport } from './routes/pibliye'
import { Route as NotifikasyonRouteImport } from './routes/notifikasyon'
import { Route as MacheRouteImport } from './routes/mache'
import { Route as KontRouteImport } from './routes/kont'
import { Route as KonekteRouteImport } from './routes/konekte'
import { Route as EnskriRouteImport } from './routes/enskri'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AbonmanRouteImport } from './routes/abonman'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PwodwiIdRouteImport } from './routes/pwodwi.$id'
import { Route as MagazenIdRouteImport } from './routes/magazen.$id'
import { Route as KontPwofilRouteImport } from './routes/kont.pwofil'
import { Route as KontPwodwiRouteImport } from './routes/kont.pwodwi'
import { Route as KontFavoriRouteImport } from './routes/kont.favori'
import { Route as AdminAnonsRouteImport } from './routes/admin.anons'

const PibliyeRoute = PibliyeRouteImport.update({
  id: '/pibliye',
  path: '/pibliye',
  getParentRoute: () => rootRouteImport,
} as any)
const NotifikasyonRoute = NotifikasyonRouteImport.update({
  id: '/notifikasyon',
  path: '/notifikasyon',
  getParentRoute: () => rootRouteImport,
} as any)
const MacheRoute = MacheRouteImport.update({
  id: '/mache',
  path: '/mache',
  getParentRoute: () => rootRouteImport,
} as any)
const KontRoute = KontRouteImport.update({
  id: '/kont',
  path: '/kont',
  getParentRoute: () => rootRouteImport,
} as any)
const KonekteRoute = KonekteRouteImport.update({
  id: '/konekte',
  path: '/konekte',
  getParentRoute: () => rootRouteImport,
} as any)
const EnskriRoute = EnskriRouteImport.update({
  id: '/enskri',
  path: '/enskri',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AbonmanRoute = AbonmanRouteImport.update({
  id: '/abonman',
  path: '/abonman',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PwodwiIdRoute = PwodwiIdRouteImport.update({
  id: '/pwodwi/$id',
  path: '/pwodwi/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const MagazenIdRoute = MagazenIdRouteImport.update({
  id: '/magazen/$id',
  path: '/magazen/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const KontPwofilRoute = KontPwofilRouteImport.update({
  id: '/pwofil',
  path: '/pwofil',
  getParentRoute: () => KontRoute,
} as any)
const KontPwodwiRoute = KontPwodwiRouteImport.update({
  id: '/pwodwi',
  path: '/pwodwi',
  getParentRoute: () => KontRoute,
} as any)
const KontFavoriRoute = KontFavoriRouteImport.update({
  id: '/favori',
  path: '/favori',
  getParentRoute: () => KontRoute,
} as any)
const AdminAnonsRoute = AdminAnonsRouteImport.update({
  id: '/anons',
  path: '/anons',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/abonman': typeof AbonmanRoute
  '/admin': typeof AdminRouteWithChildren
  '/enskri': typeof EnskriRoute
  '/konekte': typeof KonekteRoute
  '/kont': typeof KontRouteWithChildren
  '/mache': typeof MacheRoute
  '/notifikasyon': typeof NotifikasyonRoute
  '/pibliye': typeof PibliyeRoute
  '/admin/anons': typeof AdminAnonsRoute
  '/kont/favori': typeof KontFavoriRoute
  '/kont/pwodwi': typeof KontPwodwiRoute
  '/kont/pwofil': typeof KontPwofilRoute
  '/magazen/$id': typeof MagazenIdRoute
  '/pwodwi/$id': typeof PwodwiIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/abonman': typeof AbonmanRoute
  '/admin': typeof AdminRouteWithChildren
  '/enskri': typeof EnskriRoute
  '/konekte': typeof KonekteRoute
  '/kont': typeof KontRouteWithChildren
  '/mache': typeof MacheRoute
  '/notifikasyon': typeof NotifikasyonRoute
  '/pibliye': typeof PibliyeRoute
  '/admin/anons': typeof AdminAnonsRoute
  '/kont/favori': typeof KontFavoriRoute
  '/kont/pwodwi': typeof KontPwodwiRoute
  '/kont/pwofil': typeof KontPwofilRoute
  '/magazen/$id': typeof MagazenIdRoute
  '/pwodwi/$id': typeof PwodwiIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/abonman': typeof AbonmanRoute
  '/admin': typeof AdminRouteWithChildren
  '/enskri': typeof EnskriRoute
  '/konekte': typeof KonekteRoute
  '/kont': typeof KontRouteWithChildren
  '/mache': typeof MacheRoute
  '/notifikasyon': typeof NotifikasyonRoute
  '/pibliye': typeof PibliyeRoute
  '/admin/anons': typeof AdminAnonsRoute
  '/kont/favori': typeof KontFavoriRoute
  '/kont/pwodwi': typeof KontPwodwiRoute
  '/kont/pwofil': typeof KontPwofilRoute
  '/magazen/$id': typeof MagazenIdRoute
  '/pwodwi/$id': typeof PwodwiIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/abonman'
    | '/admin'
    | '/enskri'
    | '/konekte'
    | '/kont'
    | '/mache'
    | '/notifikasyon'
    | '/pibliye'
    | '/admin/anons'
    | '/kont/favori'
    | '/kont/pwodwi'
    | '/kont/pwofil'
    | '/magazen/$id'
    | '/pwodwi/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/abonman'
    | '/admin'
    | '/enskri'
    | '/konekte'
    | '/kont'
    | '/mache'
    | '/notifikasyon'
    | '/pibliye'
    | '/admin/anons'
    | '/kont/favori'
    | '/kont/pwodwi'
    | '/kont/pwofil'
    | '/magazen/$id'
    | '/pwodwi/$id'
  id:
    | '__root__'
    | '/'
    | '/abonman'
    | '/admin'
    | '/enskri'
    | '/konekte'
    | '/kont'
    | '/mache'
    | '/notifikasyon'
    | '/pibliye'
    | '/admin/anons'
    | '/kont/favori'
    | '/kont/pwodwi'
    | '/kont/pwofil'
    | '/magazen/$id'
    | '/pwodwi/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AbonmanRoute: typeof AbonmanRoute
  AdminRoute: typeof AdminRouteWithChildren
  EnskriRoute: typeof EnskriRoute
  KonekteRoute: typeof KonekteRoute
  KontRoute: typeof KontRouteWithChildren
  MacheRoute: typeof MacheRoute
  NotifikasyonRoute: typeof NotifikasyonRoute
  PibliyeRoute: typeof PibliyeRoute
  MagazenIdRoute: typeof MagazenIdRoute
  PwodwiIdRoute: typeof PwodwiIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pibliye': {
      id: '/pibliye'
      path: '/pibliye'
      fullPath: '/pibliye'
      preLoaderRoute: typeof PibliyeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifikasyon': {
      id: '/notifikasyon'
      path: '/notifikasyon'
      fullPath: '/notifikasyon'
      preLoaderRoute: typeof NotifikasyonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mache': {
      id: '/mache'
      path: '/mache'
      fullPath: '/mache'
      preLoaderRoute: typeof MacheRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kont': {
      id: '/kont'
      path: '/kont'
      fullPath: '/kont'
      preLoaderRoute: typeof KontRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/konekte': {
      id: '/konekte'
      path: '/konekte'
      fullPath: '/konekte'
      preLoaderRoute: typeof KonekteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/enskri': {
      id: '/enskri'
      path: '/enskri'
      fullPath: '/enskri'
      preLoaderRoute: typeof EnskriRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/abonman': {
      id: '/abonman'
      path: '/abonman'
      fullPath: '/abonman'
      preLoaderRoute: typeof AbonmanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pwodwi/$id': {
      id: '/pwodwi/$id'
      path: '/pwodwi/$id'
      fullPath: '/pwodwi/$id'
      preLoaderRoute: typeof PwodwiIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/magazen/$id': {
      id: '/magazen/$id'
      path: '/magazen/$id'
      fullPath: '/magazen/$id'
      preLoaderRoute: typeof MagazenIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kont/pwofil': {
      id: '/kont/pwofil'
      path: '/pwofil'
      fullPath: '/kont/pwofil'
      preLoaderRoute: typeof KontPwofilRouteImport
      parentRoute: typeof KontRoute
    }
    '/kont/pwodwi': {
      id: '/kont/pwodwi'
      path: '/pwodwi'
      fullPath: '/kont/pwodwi'
      preLoaderRoute: typeof KontPwodwiRouteImport
      parentRoute: typeof KontRoute
    }
    '/kont/favori': {
      id: '/kont/favori'
      path: '/favori'
      fullPath: '/kont/favori'
      preLoaderRoute: typeof KontFavoriRouteImport
      parentRoute: typeof KontRoute
    }
    '/admin/anons': {
      id: '/admin/anons'
      path: '/anons'
      fullPath: '/admin/anons'
      preLoaderRoute: typeof AdminAnonsRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAnonsRoute: typeof AdminAnonsRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAnonsRoute: AdminAnonsRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface KontRouteChildren {
  KontFavoriRoute: typeof KontFavoriRoute
  KontPwodwiRoute: typeof KontPwodwiRoute
  KontPwofilRoute: typeof KontPwofilRoute
}

const KontRouteChildren: KontRouteChildren = {
  KontFavoriRoute: KontFavoriRoute,
  KontPwodwiRoute: KontPwodwiRoute,
  KontPwofilRoute: KontPwofilRoute,
}

const KontRouteWithChildren = KontRoute._addFileChildren(KontRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AbonmanRoute: AbonmanRoute,
  AdminRoute: AdminRouteWithChildren,
  EnskriRoute: EnskriRoute,
  KonekteRoute: KonekteRoute,
  KontRoute: KontRouteWithChildren,
  MacheRoute: MacheRoute,
  NotifikasyonRoute: NotifikasyonRoute,
  PibliyeRoute: PibliyeRoute,
  MagazenIdRoute: MagazenIdRoute,
  PwodwiIdRoute: PwodwiIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
